// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3vFf6M7ZriR-hqTr225vzBTa4e_D_LY',
    appId: '1:485545826010:web:d55e0f59219d7bdd5fb7e3',
    messagingSenderId: '485545826010',
    projectId: 'dun-dee-application',
    authDomain: 'dun-dee-application.firebaseapp.com',
    storageBucket: 'dun-dee-application.firebasestorage.app',
    measurementId: 'G-JMD2559NCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4SbM7f623s5uRqqTujRVIwb8zRvZghE',
    appId: '1:485545826010:android:6c7ae092a3584e3f5fb7e3',
    messagingSenderId: '485545826010',
    projectId: 'dun-dee-application',
    storageBucket: 'dun-dee-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhKdtgf89zrJhQC4oZQqrPVeZr2LxMoEk',
    appId: '1:485545826010:ios:66574820089d28d15fb7e3',
    messagingSenderId: '485545826010',
    projectId: 'dun-dee-application',
    storageBucket: 'dun-dee-application.firebasestorage.app',
    iosBundleId: 'com.example.dunDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhKdtgf89zrJhQC4oZQqrPVeZr2LxMoEk',
    appId: '1:485545826010:ios:66574820089d28d15fb7e3',
    messagingSenderId: '485545826010',
    projectId: 'dun-dee-application',
    storageBucket: 'dun-dee-application.firebasestorage.app',
    iosBundleId: 'com.example.dunDiaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ3vFf6M7ZriR-hqTr225vzBTa4e_D_LY',
    appId: '1:485545826010:web:0a7ab9992ca83e385fb7e3',
    messagingSenderId: '485545826010',
    projectId: 'dun-dee-application',
    authDomain: 'dun-dee-application.firebaseapp.com',
    storageBucket: 'dun-dee-application.firebasestorage.app',
    measurementId: 'G-LYS2GF9K75',
  );
}
